import json, urllib.request

# Check submission 1 report
req = urllib.request.Request(
    'http://localhost:8000/api/homework/reports/1',
    headers={'X-API-Key': 'sk_a289e915bee24eba9d05061f35fea7f1'}
)
resp = urllib.request.urlopen(req)
data = json.loads(resp.read().decode('utf-8'))
print('Feedback:', data['data']['feedback'][:60])
print('Generated by:', data['data']['generated_by'])
print('Score:', data['data']['score'])

with open('D:\\ischen_code\\study-monitor\\report_check.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('Written to report_check.json')
